### PR TITLE
fix issue:func in handleRequest caused nil pointer panic.

### PR DESCRIPTION
**Pull request by JamesYin689**
Handling unexpected ack message caused panic.
微信图片_20210910103034

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
@JamesYin689 Hey, Thank you for your PR, can you explain the scene of `caused nil pointer panic`, I need to make sure that removing this piece of code will not cause another issue.

**Comment by JamesYin689** [comment]
Hi @cloudwebrtc, thanks for your reply.
The scene is like this:
1) A-----INVITE----> B
2) A<----715-------- B  (The contact address in B's answer is wrong, the address is A's address)
3) A-----ACK-------->A

I know B's answer is wrong,but I can't restrict it from doing so.
I don't know what the "go func" here does, but I compared the function "handleRequest" with elder version, the elder one doesn't have the code.

The complete log is as follows:

[0;90m[2021-09-08 22:23:42.709][0m [0;34mDEBUG[0m[0;36m transport.Layer:[0m sending SIP request:
INVITE sip:070310000003010002@172.37.40.251:21122;transport=udp SIP/2.0
Via: SIP/2.0/UDP 172.37.40.251:21113;branch=z9hG4bK.VXT7FV8CliWHP7JfYv631T3A9sjGJHbd
CSeq: 1 INVITE
From: <sip:100010000004020002@172.37.40.251:21113>;tag=jPHCzeDS
To: <sip:070310000003010002@172.37.40.251:21122>
Call-ID: b9e32035-ed90-40e8-9fa9-56ac1a4baa81
Contact: <sip:100010000004020002@172.37.40.251:21113>
Max-Forwards: 70
User-Agent: GoSIP
Content-Length: 428
Content-Type: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, INFO, OPTIONS, MESSAGE, REGISTER, NOTIFY
Supported: replaces, outbound

v=0
o=- 0 0 IN IP4 172.37.40.251
s=Playback
u=rtsp://172.37.40.251:21120/070310000003010002/172.37.40.251:21120/100010000004020002/070310000003010002/172.29.130.35:7525/0703100000030100020002065.00070310000003010002ch01_00000000055000000
c=IN IP4 172.37.40.251
t=0 0
a=range:ntp=0-0
a=mime:.trtp
m=video 23246 RTP/AVP 100
y=2000000687
a=rtpmap:100 H264/90000
a=fmtp:100 CIF=1;4CIF=1;F=1;K=1
a=recvonly
a=rate:main
 [0;34mdestination[0m=172.37.40.251:21122 [0;34mprotocol_ptr[0m=0xc00048c000 [0;34mrequest_id[0m=d92c7a25-a778-41a5-8adc-4b79b25602d4 [0;34msource[0m=172.37.40.251:21113 [0;34mtransaction_key[0m=z9hG4bK.VXT7FV8CliWHP7JfYv631T3A9sjGJHbd__INVITE [0;34mtransaction_ptr[0m=0xc000422900 [0;34mtransport[0m=UDP [0;34mtransport_layer_ptr[0m=0xc0003d7440
[0;90m[2021-09-08 22:23:42.709][0m [0;34mDEBUG[0m[0;36m transaction.Layer:[0m start serve transaction [0;34mdestination[0m=172.37.40.251:21122 [0;34mrequest_id[0m=d92c7a25-a778-41a5-8adc-4b79b25602d4 [0;34msource[0m=172.37.40.251:21113 [0;34mtransaction_key[0m=z9hG4bK.VXT7FV8CliWHP7JfYv631T3A9sjGJHbd__INVITE [0;34mtransaction_layer_ptr[0m=0xc00040cf80 [0;34mtransaction_ptr[0m=0xc000422900 [0;34mtransport[0m=UDP
[0;90m[2021-09-08 22:23:42.830][0m [0;34mDEBUG[0m[0;36m transport.Layer:[0m received SIP message:
SIP/2.0 715 OK
Via: SIP/2.0/UDP 172.37.40.251:21113;branch=z9hG4bK.VXT7FV8CliWHP7JfYv631T3A9sjGJHbd
CSeq: 1 INVITE
From: <sip:100010000004020002@172.37.40.251:21113>;tag=jPHCzeDS
To: <sip:070310000003010002@172.37.40.251:21122>;tag=20b0660
Call-ID: b9e32035-ed90-40e8-9fa9-56ac1a4baa81
Contact: <sip:100010000004020002@172.37.40.251:21113>
Max-Forwards: 68
User-Agent: GoSIP
Content-Length: 428
Content-Type: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, INFO, OPTIONS, MESSAGE, REGISTER, NOTIFY
Supported: replaces, outbound

v=0
o=- 0 0 IN IP4 172.37.40.251
s=Playback
u=rtsp://172.37.40.251:21120/070310000003010002/172.37.40.251:21120/100010000004020002/070310000003010002/172.29.130.35:7525/0703100000030100020002065.00070310000003010002ch01_00000000055000000
c=IN IP4 172.37.40.251
t=0 0
a=range:ntp=0-0
a=mime:.trtp
m=video 23246 RTP/AVP 100
y=2000000687
a=rtpmap:100 H264/90000
a=fmtp:100 CIF=1;4CIF=1;F=1;K=1
a=recvonly
a=rate:main
 [0;34mconnection_key[0m=udp:0.0.0.0:21113 [0;34mdestination[0m=172.37.40.251:21113 [0;34mreceived_at[0m=2021-09-08 22:23:42.830566807 +0800 CST m=+12531.008054731 [0;34mresponse_id[0m=3a8885bb-5709-424f-b888-5479d3142454 [0;34msource[0m=172.37.40.251:21122 [0;34mtransport[0m=UDP [0;34mtransport_layer_ptr[0m=0xc0003d7440
[0;90m[2021-09-08 22:23:42.830][0m [0;34mDEBUG[0m[0;36m transaction.Layer:[0m handling SIP message [0;34mconnection_key[0m=udp:0.0.0.0:21113 [0;34mdestination[0m=172.37.40.251:21113 [0;34mreceived_at[0m=2021-09-08 22:23:42.830566807 +0800 CST m=+12531.008054731 [0;34mresponse_id[0m=3a8885bb-5709-424f-b888-5479d3142454 [0;34msource[0m=172.37.40.251:21122 [0;34mtransaction_layer_ptr[0m=0xc00040cf80 [0;34mtransport[0m=UDP
[0;90m[2021-09-08 22:23:42.830][0m [0;34mDEBUG[0m[0;36m transaction.ClientTx:[0m act_invite_final [0;34mdestination[0m=172.37.40.251:21122 [0;34mrequest_id[0m=d92c7a25-a778-41a5-8adc-4b79b25602d4 [0;34msource[0m=172.37.40.251:21113 [0;34mtransaction_key[0m=z9hG4bK.VXT7FV8CliWHP7JfYv631T3A9sjGJHbd__INVITE [0;34mtransaction_layer_ptr[0m=0xc00040cf80 [0;34mtransaction_ptr[0m=0xc000422900 [0;34mtransport[0m=UDP
[0;90m[2021-09-08 22:23:42.831][0m [0;34mDEBUG[0m[0;36m transport.Layer:[0m sending SIP request:
ACK sip:100010000004020002@172.37.40.251:21113 SIP/2.0
Via: SIP/2.0/UDP 172.37.40.251:21113;branch=z9hG4bK.VXT7FV8CliWHP7JfYv631T3A9sjGJHbd
Max-Forwards: 70
From: <sip:100010000004020002@172.37.40.251:21113>;tag=jPHCzeDS
To: <sip:070310000003010002@172.37.40.251:21122>;tag=20b0660
Call-ID: b9e32035-ed90-40e8-9fa9-56ac1a4baa81
CSeq: 1 ACK
Content-Length: 0
User-Agent: Go SipStack/1.0.0

 [0;34mdestination[0m= [0;34minvite_request_id[0m=d92c7a25-a778-41a5-8adc-4b79b25602d4 [0;34minvite_response_id[0m=3a8885bb-5709-424f-b888-5479d3142454 [0;34mprotocol_ptr[0m=0xc00048c000 [0;34mrequest_id[0m=32e745d8-4bd4-45c6-9379-2e3c951c15f6 [0;34msent_at[0m=2021-09-08 22:23:42.830907834 +0800 CST m=+12531.008395744 [0;34msource[0m= [0;34mtransaction_key[0m=z9hG4bK.VXT7FV8CliWHP7JfYv631T3A9sjGJHbd__INVITE [0;34mtransaction_ptr[0m=0xc000422900 [0;34mtransport[0m= [0;34mtransport_layer_ptr[0m=0xc0003d7440
[0;90m[2021-09-08 22:23:42.831][0m [0;34mDEBUG[0m[0;36m transport.Layer:[0m received SIP message:
ACK sip:100010000004020002@172.37.40.251:21113 SIP/2.0
Via: SIP/2.0/UDP 172.37.40.251:21113;branch=z9hG4bK.VXT7FV8CliWHP7JfYv631T3A9sjGJHbd;received=172.37.40.251
Max-Forwards: 70
From: <sip:100010000004020002@172.37.40.251:21113>;tag=jPHCzeDS
To: <sip:070310000003010002@172.37.40.251:21122>;tag=20b0660
Call-ID: b9e32035-ed90-40e8-9fa9-56ac1a4baa81
CSeq: 1 ACK
Content-Length: 0
User-Agent: Go SipStack/1.0.0

 [0;34mconnection_key[0m=udp:0.0.0.0:21113 [0;34mdestination[0m=172.37.40.251:21113 [0;34mreceived_at[0m=2021-09-08 22:23:42.831292941 +0800 CST m=+12531.008780874 [0;34mrequest_id[0m=acb6a5c9-bf73-4766-8d1d-0a598678ae3c [0;34msource[0m=172.37.40.251:21113 [0;34mtransport[0m=UDP [0;34mtransport_layer_ptr[0m=0xc0003d7440
[0;90m[2021-09-08 22:23:42.831][0m [0;34mDEBUG[0m[0;36m transaction.Layer:[0m handling SIP message [0;34mconnection_key[0m=udp:0.0.0.0:21113 [0;34mdestination[0m=172.37.40.251:21113 [0;34mreceived_at[0m=2021-09-08 22:23:42.831292941 +0800 CST m=+12531.008780874 [0;34mrequest_id[0m=acb6a5c9-bf73-4766-8d1d-0a598678ae3c [0;34msource[0m=172.37.40.251:21113 [0;34mtransaction_layer_ptr[0m=0xc00040cf80 [0;34mtransport[0m=UDP
[0;90m[2021-09-08 22:23:42.831][0m [0;34mDEBUG[0m[0;36m SipStack:[0m routing incoming SIP request... [0;34mconnection_key[0m=udp:0.0.0.0:21113 [0;34mdestination[0m=172.37.40.251:21113 [0;34mreceived_at[0m=2021-09-08 22:23:42.831292941 +0800 CST m=+12531.008780874 [0;34mrequest_id[0m=acb6a5c9-bf73-4766-8d1d-0a598678ae3c [0;34msource[0m=172.37.40.251:21113 [0;34mtransport[0m=UDP
[0;90m[2021-09-08 22:23:42.831][0m [0;33m WARN[0m[0;36m SipStack:[0m SIP request ACK handler not found [0;33mconnection_key[0m=udp:0.0.0.0:21113 [0;33mdestination[0m=172.37.40.251:21113 [0;33mreceived_at[0m=2021-09-08 22:23:42.831292941 +0800 CST m=+12531.008780874 [0;33mrequest_id[0m=acb6a5c9-bf73-4766-8d1d-0a598678ae3c [0;33msource[0m=172.37.40.251:21113 [0;33mtransport[0m=UDP
[0;90m[2021-09-08 22:23:42.831][0m [0;31mERROR[0m[0;36m SipStack:[0m respond '405 Method Not Allowed' failed: transaction.Layer<transaction_layer_ptr=0xc00040cf80> failed to match message 'sip.Response<transport=UDP sequence=1 status=405 reason=Method Not Allowed response_id=d9c28e81-60b6-45ec-96b4-48c25af7372a source=172.37.40.251:21113 received_at=2021-09-08 22:23:42.831292941 +0800 CST m=+12531.008780874 method=ACK destination=172.37.40.251:21113 request_id=acb6a5c9-bf73-4766-8d1d-0a598678ae3c connection_key=udp:0.0.0.0:21113>' to server transaction: transaction with key 'z9hG4bK.VXT7FV8CliWHP7JfYv631T3A9sjGJHbd__172.37.40.251__21113__INVITE' not found [0;31mconnection_key[0m=udp:0.0.0.0:21113 [0;31mdestination[0m=172.37.40.251:21113 [0;31mreceived_at[0m=2021-09-08 22:23:42.831292941 +0800 CST m=+12531.008780874 [0;31mrequest_id[0m=acb6a5c9-bf73-4766-8d1d-0a598678ae3c [0;31msource[0m=172.37.40.251:21113 [0;31mtransport[0m=UDP
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x943456]

goroutine 28024 [running]:
github.com/cloudwebrtc/go-sip-ua/pkg/stack.(*SipStack).handleRequest.func1(0xc00052e540, 0x0, 0x0, 0xefa840, 0xc000595590)
	/mnt/hgfs/GoProject/ivss/ivss/vendor/github.com/cloudwebrtc/go-sip-ua/pkg/stack/stack.go:260 +0xa6
created by github.com/cloudwebrtc/go-sip-ua/pkg/stack.(*SipStack).handleRequest
	/mnt/hgfs/GoProject/ivss/ivss/vendor/github.com/cloudwebrtc/go-sip-ua/pkg/stack/stack.go:255 +0x3fb

**Comment by cloudwebrtc** [comment]
you can try to add a breakpoint, first find out why the tx pointer is `nil`, which seems to be the key to the exception.
```go
}(tx, logger)
```
This goroutine is to confirm that the transaction was completed normally or ended in error, so I think we don't need to remove the code segment, we should look for why tx is `nil`.

**Comment by JamesYin689** [comment]
原因就在于A收到了自己的Ack。serve里处理ack时 handleRequest传的就是nil。

**Comment by cloudwebrtc** [comment]
> 原因就在于A收到了自己的Ack。serve里处理ack时 handleRequest传的就是nil。

所以我觉得这里比较合理的处理方法是，当没有注册handler for ACK时, 判断 tx 不为空, 避免panic.
因为ACK 确实不需要 确认transaction 是否完成.

```go
if tx != nil {
  go func(tx sip.ServerTransaction, logger log.Logger) {
     ...
  }(tx, logger)
}
```

而在实际 UA 处理中您应该加上 ACK， 来确认INVITE 已经完成.

https://github.com/cloudwebrtc/go-sip-ua/blob/master/pkg/ua/ua.go#L248

**Comment by JamesYin689** [comment]
是的，这样改也可以，但是这个协程没看出来有啥用，担心协程会泄漏，我先把PR关了吧。
if tx != nil {
  go func(tx sip.ServerTransaction, logger log.Logger) {
     ...
  }(tx, logger)
}

**Pull request closed without merging**
